// Anchor Behavior Rubric — 39 blocks
// clinical: dùng khi isClinic=true (L0 only)
// behavioral: dùng cho tất cả
// rows: dùng cho L1–L7 (không có clinical/behavioral split)

export interface AnchorEntry {
  name:       string
  clinical?:  string[]  // L0 only
  behavioral?: string[] // L0 only
  rows?:      string[]  // L1–L7
}

export const ANCHOR: Record<string, AnchorEntry> = {
  sleep: { name: 'Sleep — Giấc ngủ',
    clinical: [
      'Rối loạn giấc ngủ nặng được chẩn đoán (polysomnography, sleep diary). Cần can thiệp y tế.',
      'Rối loạn giấc ngủ trung bình theo ghi nhận lâm sàng. Chưa chẩn đoán chính thức nhưng chỉ số bất thường rõ.',
      'Giấc ngủ không đều theo sleep diary. Chưa đến ngưỡng rối loạn lâm sàng.',
      'Giấc ngủ tương đối tốt theo ghi nhận. Không cần can thiệp y tế.',
      'Giấc ngủ tốt, tất cả chỉ số trong giới hạn bình thường.',
    ],
    behavioral: [
      'Vào giấc >60 phút, cần can thiệp mạnh (bế, ru liên tục). Thức >4 lần/đêm, khó ngủ lại >30 phút. Thức giấc hoảng loạn. Không ngủ trưa được dù cần thiết theo lứa tuổi hoặc ngủ trưa >3 giờ gây đảo lộn giấc đêm.',
      'Vào giấc 45–60 phút, cần nghi thức phức tạp. Thức 2–4 lần/đêm, khó ngủ lại 15–30 phút. Cần đánh thức nhiều lần, thức giấc khóc/la hét thường xuyên. Ngủ trưa không đều, ảnh hưởng giấc đêm.',
      'Vào giấc 30–45 phút, cần nghi thức đơn giản. Thức 1–2 lần/đêm, ngủ lại được trong <15 phút. Cần đánh thức 1–2 lần, thỉnh thoảng cáu kỉnh khi thức. Ngủ trưa được nhưng không đều.',
      'Vào giấc 15–30 phút, nghi thức đơn giản nhất quán. Thức <1 lần/đêm, ngủ lại ngay. Tự thức hoặc cần đánh thức 1 lần nhẹ. Ngủ trưa đều đặn phù hợp lứa tuổi.',
      'Vào giấc <15 phút, không cần nghi thức đặc biệt. Không thức hoặc thức rất hiếm (<1 lần/tuần). Tự thức đúng giờ, tỉnh táo. Ngủ trưa đúng nhu cầu lứa tuổi hoặc tự điều chỉnh.',
    ]},
  microbiome: { name: 'Microbiome — Vi sinh đường ruột',
    clinical: [
      'Dysbiosis nặng được xác nhận qua xét nghiệm vi sinh. Calprotectin cao. Bệnh lý đường ruột được chẩn đoán. Tiền sử dùng kháng sinh liên tục.',
      'Dysbiosis trung bình hoặc nguy cơ cao theo xét nghiệm. Tiền sử kháng sinh gần đây.',
      'Microbiome chưa cân bằng nhưng không có chẩn đoán. Nguy cơ trung bình theo chỉ số.',
      'Microbiome tương đối cân bằng theo xét nghiệm. Không có dấu hiệu bất thường rõ.',
      'Microbiome cân bằng tốt hoặc xét nghiệm bình thường. Không có tiền sử bệnh lý đường ruột.',
    ],
    behavioral: [
      'Đau bụng hàng ngày. Tiêu chảy hoặc táo bón nặng liên tục. Nôn thường xuyên. Từ chối ăn do đau.',
      'Đau bụng/khó chịu >3 lần/tuần. Phân không đều thường xuyên. Thỉnh thoảng nôn hoặc buồn nôn.',
      'Khó chịu tiêu hóa 1–2 lần/tuần. Phân không đều nhưng không nghiêm trọng. Ăn uống được với một số giới hạn.',
      'Tiêu hóa tương đối ổn. Vấn đề nhỏ không thường xuyên. Ăn uống đa dạng không bị giới hạn nhiều.',
      'Tiêu hóa ổn định. Phân đều đặn. Không đau bụng. Ăn uống đa dạng không hạn chế.',
    ]},
  nutrition: { name: 'Nutrition — Dinh dưỡng',
    clinical: [
      'Thiếu hụt vi chất nghiêm trọng được xác nhận qua xét nghiệm. Z-score <-3. Cần can thiệp dinh dưỡng y tế.',
      'Thiếu hụt vi chất trung bình. Z-score -2 đến -3. Một hoặc nhiều vi chất bất thường.',
      'Thiếu vi chất nhẹ hoặc nguy cơ. Z-score -1 đến -2. Chỉ số dinh dưỡng chưa tối ưu.',
      'Dinh dưỡng đủ, không có thiếu hụt đáng kể. Z-score trong giới hạn bình thường.',
      'Dinh dưỡng tốt, đầy đủ và cân đối. Z-score tối ưu. Không có thiếu hụt vi chất.',
    ],
    behavioral: [
      'Chấp nhận <5 loại thực phẩm. Từ chối toàn bộ nhóm thực phẩm. Dấu hiệu thiếu dinh dưỡng rõ (tóc, da, năng lượng thấp).',
      'Chấp nhận 5–10 loại. Thiếu 1–2 nhóm thực phẩm chính. Không đủ năng lượng cho lứa tuổi.',
      'Chấp nhận 10–15 loại. Có sở thích/từ chối rõ nhưng đủ nhóm cơ bản. Dinh dưỡng tạm đủ.',
      'Chấp nhận >15 loại. Ăn được hầu hết nhóm. Tăng trưởng đúng đường cong.',
      'Ăn đa dạng không hạn chế đáng kể. Tăng trưởng tốt. Không có dấu hiệu thiếu hụt.',
    ]},
  immune: { name: 'Immune — Miễn dịch',
    clinical: [
      'Suy giảm miễn dịch được chẩn đoán. Dị ứng nặng/bệnh tự miễn ảnh hưởng sinh hoạt hàng ngày. CBC bất thường.',
      'Miễn dịch suy giảm nhẹ theo xét nghiệm. Dị ứng trung bình có chẩn đoán.',
      'Không có chẩn đoán nhưng chỉ số nguy cơ. Dị ứng nhẹ kiểm soát được.',
      'Miễn dịch tốt theo xét nghiệm. Không có chẩn đoán dị ứng/tự miễn.',
      'Miễn dịch tốt. CBC bình thường. Không có tiền sử bệnh lý miễn dịch.',
    ],
    behavioral: [
      'Bệnh >4 lần/tháng, mỗi lần kéo dài >2 tuần. Không thể đến trường/trị liệu thường xuyên.',
      'Bệnh 2–4 lần/tháng. Phục hồi 1–2 tuần. Dị ứng ảnh hưởng hoạt động hàng ngày.',
      'Bệnh 1–2 lần/tháng. Phục hồi trong 1 tuần. Dị ứng theo mùa, kiểm soát được.',
      'Bệnh 1–2 lần/quý. Phục hồi nhanh <1 tuần. Không có dị ứng đáng kể.',
      'Hiếm khi bệnh. Phục hồi trong 2–3 ngày. Không có dị ứng.',
    ]},
  metabolic: { name: 'Metabolic — Chuyển hóa',
    clinical: [
      'Rối loạn chuyển hóa được chẩn đoán (tiểu đường, suy giáp, béo phì bệnh lý). Chỉ số đường huyết/TSH/BMI bất thường rõ. Cần can thiệp y tế.',
      'Chỉ số cận lâm sàng bất thường chưa đến ngưỡng chẩn đoán. BMI ngoài giới hạn bình thường.',
      'Chỉ số trong giới hạn nhưng có xu hướng bất thường. BMI biên. Cần theo dõi.',
      'Tất cả chỉ số trong giới hạn bình thường. BMI phù hợp lứa tuổi.',
      'Chỉ số chuyển hóa tối ưu. BMI lý tưởng. Không có tiền sử rối loạn chuyển hóa.',
    ],
    behavioral: [
      'Mệt mỏi mãn tính không giải thích được. Không duy trì hoạt động >15 phút. Cân nặng biến động >10% không giải thích.',
      'Năng lượng thấp, mệt sau hoạt động nhẹ. Cần nghỉ thường xuyên. Khó duy trì hoạt động >30 phút.',
      'Năng lượng không đều trong ngày. Mệt sau buổi chiều. Cân nặng ổn nhưng có biến động nhỏ.',
      'Năng lượng tương đối ổn định. Cân nặng ổn. Duy trì hoạt động suốt ngày với nghỉ bình thường.',
      'Năng lượng ổn định và đủ suốt ngày. Cân nặng ổn định. Không có dấu hiệu rối loạn chuyển hóa.',
    ]},
  arousal: { name: 'Arousal — Điều tiết kích thích', rows: [
    'Arousal cực kỳ không ổn định. Liên tục hyper hoặc liên tục hypo. Không thể phục hồi về baseline trong session.',
    'Arousal không ổn định, ảnh hưởng rõ đến khả năng tham gia. Chuyển đổi hyper/hypo thường xuyên. Phục hồi chậm >10 phút.',
    'Arousal dao động nhưng kiểm soát được một phần. Cần nhắc nhở định kỳ. Phục hồi 5–10 phút.',
    'Arousal tương đối ổn định. Tham gia được hoạt động có cấu trúc. Phục hồi <5 phút.',
    'Arousal ổn định và phù hợp ngữ cảnh. Tự điều chỉnh được. Duy trì trạng thái tỉnh táo suốt session.',
  ]},
  reflex_survival: { name: 'Reflex — Survival (Moro · Rooting · Galant)', rows: [
    'Phản ứng mạnh ở cả 3 phản xạ. Moro: từ chối/đông cứng khi test. Rooting: phản ứng mạnh má/cổ/tay. Galant: cong người mạnh, kêu đau hoặc từ chối.',
    'Phản ứng rõ ở 2/3 phản xạ. Moro: giật mình mạnh. Rooting: phản ứng tương đối. Galant: cong người tương đối, hông nhúc nhích rõ.',
    'Phản ứng nhẹ ở 1–2 phản xạ. Moro: nín thở, chuyển động có kiểm soát một phần. Rooting: ít. Galant: chuyển động nhẹ.',
    'Phản ứng rất nhẹ, không ảnh hưởng chức năng. Moro: hơi giật nhẹ. Rooting: rất ít. Galant: hầu như không phản ứng.',
    'Không có phản ứng bất thường ở cả 3 phản xạ. Tích hợp hoàn toàn.',
  ]},
  reflex_postural: { name: 'Reflex — Postural (ATNR · STNR · TLR · Landau)', rows: [
    'Phản ứng rõ ở hầu hết phản xạ. ATNR: tay gập hoàn toàn, hông rung lắc. STNR: rung lắc mạnh toàn thân. TLR: không giữ được >5 giây. Landau: không thể cô lập thân trên/dưới.',
    'Phản ứng rõ ở 2–3 phản xạ. ATNR: hơi cong tay, hông nhúc nhích. STNR: gập/duỗi khuỷu tay. TLR: giữ được ~10 giây, bất đối xứng.',
    'Phản ứng nhẹ ở 1–2 phản xạ. ATNR: chuyển động nhẹ hông/chân. STNR: nhẹ. TLR: giữ được ~20 giây.',
    'Phản ứng rất nhẹ. TLR: giữ được ~30 giây, ổn định. Landau: cô lập được, ngón chân hơi nhúc nhích.',
    'Không có phản ứng bất thường. Duy trì tốt tất cả tư thế. Cô lập thân trên/dưới hoàn toàn.',
  ]},
  reflex_cortical: { name: 'Reflex — Cortical (Palmar · Babinski · Babkin)', rows: [
    'Palmar: cong người mạnh, vùng miệng phản ứng rõ, không hợp tác. Babinski: ngón chân xòe mạnh nhất quán. Babkin: miệng mở rộng, đầu xoay mạnh.',
    'Palmar: chuyển động tương đối tay/ngón, nhúc nhích khuỷu tay hoặc vùng miệng. Babinski: ngón chân xòe tương đối. Babkin: miệng hé mở hoặc đầu xoay nhẹ.',
    'Palmar: chuyển động nhẹ tay và ngón. Babinski: ngón chân hơi xòe nhẹ. Babkin: phản ứng rất nhẹ, không nhất quán.',
    'Palmar: hơi chuyển động nhẹ ngón tay. Babinski: phản ứng rất nhẹ. Babkin: hầu như không phản ứng.',
    'Không có phản ứng bất thường ở cả 3 phản xạ. Corticospinal tract trưởng thành. Tích hợp hoàn toàn.',
  ]},
  tone: { name: 'Muscle Tone — Trương lực cơ', rows: [
    'Tone nền bất thường nặng. Hypotonia nặng: không thể chống trọng lực, xệ người. Hoặc hypertonia nặng: cứng toàn thân, không thể thả lỏng.',
    'Tone bất thường rõ. Ngồi được nhưng xệ vai, cần tựa liên tục. Hoặc di chuyển cứng, khó thay đổi tư thế.',
    'Tone hơi bất thường. Ngồi được nhưng tư thế không tối ưu. Mỏi sau 15–20 phút hoạt động.',
    'Tone tương đối bình thường. Duy trì tư thế tốt trong hầu hết hoạt động. Điều chỉnh được khi cần.',
    'Tone bình thường. Duy trì tư thế tốt trong mọi hoạt động. Không mỏi bất thường.',
  ]},
  ns_stability: { name: 'Neural Stability — Ổn định hệ thần kinh', rows: [
    'Hệ thần kinh cực kỳ không ổn định. Phản ứng mạnh với kích thích rất nhỏ. Meltdown thường xuyên. Hành vi hoàn toàn không nhất quán.',
    'Không ổn định rõ. Ngưỡng kích hoạt thấp. Phục hồi >15 phút. Biến động lớn giữa các session.',
    'Không ổn định vừa. Kiểm soát được trong môi trường có cấu trúc. Phục hồi 10–15 phút.',
    'Tương đối ổn định. Ngưỡng kích hoạt gần bình thường. Phục hồi 5–10 phút. Biến động nhỏ.',
    'Ổn định tốt. Ngưỡng kích hoạt bình thường. Phục hồi <5 phút. Nhất quán giữa các session.',
  ]},
  vestibular: { name: 'Vestibular — Tiền đình', rows: [
    'Phản ứng cực đoan với chuyển động: hoàn toàn né tránh (sợ hãi, nôn) hoặc tìm kiếm liên tục không kiểm soát. Mất thăng bằng rõ rệt.',
    'Phản ứng quá mức hoặc thiếu với chuyển động. Khó duy trì thăng bằng trong hoạt động cơ bản.',
    'Thăng bằng cơ bản đạt được nhưng không ổn định khi có thách thức. Có sở thích/né tránh nhất định.',
    'Thăng bằng tốt trong hầu hết hoạt động. Có thể có sở thích nhỏ nhưng không ảnh hưởng chức năng.',
    'Hệ tiền đình hoạt động tốt. Thăng bằng tốt trong mọi hoạt động. Xử lý chuyển động bình thường.',
  ]},
  proprioception: { name: 'Proprioception — Cảm giác bản thể', rows: [
    'Không nhận biết vị trí cơ thể trong không gian. Đụng chạm quá mạnh, không kiểm soát lực. Liên tục va chạm đồ vật/người khác.',
    'Nhận thức cơ thể kém. Thường dùng lực không phù hợp. Khó thực hiện động tác cần phán đoán lực.',
    'Nhận thức cơ thể trung bình. Kiểm soát lực không đều. Hoạt động tốt hơn trong môi trường quen.',
    'Nhận thức cơ thể tương đối tốt. Kiểm soát lực hợp lý trong hầu hết tình huống.',
    'Nhận thức cơ thể tốt. Kiểm soát lực và không gian chính xác. Tự điều chỉnh không cần nhắc.',
  ]},
  auditory: { name: 'Auditory — Thính giác', rows: [
    'Phản ứng cực đoan với âm thanh: che tai, meltdown, hoặc hoàn toàn không phản hồi âm thanh.',
    'Nhạy cảm âm thanh rõ rệt hoặc không phản hồi đủ. Môi trường ồn ào ảnh hưởng đáng kể.',
    'Có phản ứng với một số loại âm thanh nhất định. Hoạt động được trong môi trường yên tĩnh.',
    'Xử lý âm thanh tương đối tốt. Có thể có một loại gây khó chịu nhưng tự điều tiết được.',
    'Xử lý âm thanh tốt. Lọc được âm thanh nền. Không có phản ứng bất thường.',
  ]},
  visual: { name: 'Visual — Thị giác', rows: [
    'Phản ứng cực đoan với ánh sáng/thị giác. Né tránh nhìn trực tiếp hoặc bị thu hút bởi chuyển động quay liên tục.',
    'Xử lý thị giác kém. Khó theo dõi đối tượng di chuyển, khó phối hợp mắt-tay.',
    'Theo dõi thị giác cơ bản được nhưng không ổn định. Phối hợp mắt-tay cần nỗ lực.',
    'Thị giác chức năng tốt trong hầu hết hoạt động. Theo dõi và phối hợp mắt-tay ổn.',
    'Xử lý thị giác tốt. Theo dõi mượt mà, phối hợp mắt-tay chính xác.',
  ]},
  tactile: { name: 'Tactile — Xúc giác', rows: [
    'Phản ứng cực đoan với xúc giác: hoặc né tránh hoàn toàn mọi tiếp xúc, hoặc tìm kiếm kích thích mạnh liên tục.',
    'Nhạy cảm xúc giác hoặc tìm kiếm xúc giác rõ rệt. Ảnh hưởng đến mặc quần áo, cắt tóc, ăn uống.',
    'Có nhạy cảm/tìm kiếm với một số loại xúc giác cụ thể. Hoạt động được nhưng cần điều chỉnh.',
    'Xử lý xúc giác tương đối tốt. Có thể có sở thích nhỏ nhưng không ảnh hưởng sinh hoạt.',
    'Xử lý xúc giác tốt. Không có phản ứng bất thường. Tham gia đa dạng hoạt động xúc giác.',
  ]},
  interoception: { name: 'Interoception — Cảm giác nội quan', rows: [
    'Không nhận biết các tín hiệu cơ thể cơ bản: đói/no, mắc tiểu, đau, mệt. Thường xuyên có tai nạn vệ sinh.',
    'Nhận biết tín hiệu cơ thể rất kém. Thỉnh thoảng không kịp vệ sinh. Không nhận ra đói/no đúng lúc.',
    'Nhận biết được một số tín hiệu cơ thể nhưng chậm hoặc không nhất quán. Tự vệ sinh được nhưng cần nhắc.',
    'Nhận biết hầu hết tín hiệu cơ thể cơ bản. Tự quản lý vệ sinh tốt. Có thể diễn đạt đói/no/mệt.',
    'Nhận biết tốt các tín hiệu cơ thể. Tự quản lý nhu cầu sinh lý. Kết nối cảm giác với trạng thái cảm xúc.',
  ]},
  taste_smell: { name: 'Taste / Smell — Vị giác / Khứu giác', rows: [
    'Phản ứng cực đoan: nôn khi tiếp xúc với mùi/vị nhất định, hoặc ăn/liếm đồ vật không phải thức ăn (pica).',
    'Nhạy cảm mùi/vị rõ rệt. Né tránh nhiều loại thức ăn. Phản ứng tiêu cực mạnh với mùi bình thường.',
    'Có nhạy cảm nhất định. Né tránh một số nhóm thức ăn cụ thể nhưng không ảnh hưởng nghiêm trọng.',
    'Xử lý mùi/vị tương đối tốt. Có sở thích nhất định nhưng ăn được đa dạng.',
    'Xử lý mùi/vị bình thường. Ăn đa dạng. Không có phản ứng bất thường với mùi thông thường.',
  ]},
  motor_planning: { name: 'Motor Planning — Lập kế hoạch vận động', rows: [
    'Không thể thực hiện chuỗi vận động mới dù đơn giản. Không bắt chước động tác.',
    'Rất khó thực hiện vận động mới. Cần nhiều lần thử và hướng dẫn trực tiếp. Bắt chước kém.',
    'Thực hiện được vận động mới với hướng dẫn cụ thể và luyện tập nhiều lần.',
    'Học vận động mới được với hướng dẫn vừa phải. Bắt chước tương đối tốt.',
    'Lập kế hoạch và thực hiện vận động tốt. Học kỹ năng mới nhanh. Tự động hóa hiệu quả.',
  ]},
  gross_motor: { name: 'Gross Motor — Vận động thô', rows: [
    'Không đạt các mốc vận động thô cơ bản so với lứa tuổi. Không đi được độc lập.',
    'Trễ rõ vận động thô. Di chuyển được nhưng không vững. Té ngã thường xuyên.',
    'Thực hiện được các vận động thô cơ bản nhưng không khéo léo. Một số kỹ năng lứa tuổi chưa đạt.',
    'Vận động thô đủ cho sinh hoạt. Chạy, nhảy, leo cơ bản được. Có thể chậm hơn bạn cùng tuổi.',
    'Vận động thô tốt, phù hợp lứa tuổi. Tham gia được các trò chơi vận động với bạn.',
  ]},
  fine_motor: { name: 'Fine Motor — Vận động tinh', rows: [
    'Không thực hiện được vận động tinh cơ bản. Không cầm đồ vật nhỏ, không dùng muỗng, không cầm bút.',
    'Vận động tinh rất hạn chế. Cầm nắm được nhưng không kiểm soát. Cần hỗ trợ nhiều.',
    'Vận động tinh cơ bản thực hiện được nhưng chậm và mệt. Viết được nhưng khó đọc.',
    'Vận động tinh đủ cho sinh hoạt hàng ngày. Tự phục vụ cơ bản độc lập.',
    'Vận động tinh tốt, phù hợp lứa tuổi. Viết rõ, dùng kéo và dụng cụ thành thạo.',
  ]},
  postural_control: { name: 'Postural Control — Kiểm soát tư thế', rows: [
    'Không thể duy trì tư thế ngồi thẳng độc lập. Cần hỗ trợ vật lý liên tục.',
    'Ngồi được nhưng tư thế xấu rõ. Mệt cơ nhanh. Khó duy trì tư thế khi tập trung vào việc khác.',
    'Duy trì được tư thế ngồi nhưng không ổn định khi kéo dài. Tư thế giảm dần sau 10–15 phút.',
    'Duy trì tư thế ngồi tương đối tốt trong thời gian trung bình. Điều chỉnh được khi nhắc.',
    'Kiểm soát tư thế tốt. Duy trì tư thế phù hợp không cần nhắc.',
  ]},
  bilateral_coord: { name: 'Bilateral Coordination — Phối hợp hai bên', rows: [
    'Không phối hợp được hai tay/hai chân cùng lúc. Không thể dùng tay này giữ, tay kia thao tác.',
    'Phối hợp hai bên rất kém. Có xu hướng dùng một bên. Khó các hoạt động cần hai tay phối hợp.',
    'Phối hợp hai bên cơ bản được nhưng chưa nhịp nhàng. Một số kỹ năng lứa tuổi chưa đạt.',
    'Phối hợp hai bên đủ cho sinh hoạt. Có thể chậm hơn bạn cùng tuổi ở một số kỹ năng.',
    'Phối hợp hai bên tốt, phù hợp lứa tuổi. Thực hiện nhịp nhàng các hoạt động cần phối hợp.',
  ]},
  attention: { name: 'Attention Focus — Chú ý & Tập trung', rows: [
    'Không thể duy trì chú ý vào bất kỳ hoạt động nào dù trong vài giây. Không thể tham gia hoạt động có cấu trúc.',
    'Duy trì chú ý dưới 2 phút. Dễ phân tâm bởi mọi kích thích. Hiếm khi hoàn thành nhiệm vụ.',
    'Duy trì chú ý 2–5 phút với hỗ trợ. Hoàn thành nhiệm vụ ngắn khi có hỗ trợ liên tục.',
    'Duy trì chú ý 5–15 phút. Hoàn thành nhiệm vụ với hỗ trợ vừa phải.',
    'Duy trì chú ý phù hợp lứa tuổi. Tự điều chỉnh. Hoàn thành nhiệm vụ độc lập.',
  ]},
  auditory_processing: { name: 'Auditory Processing — Xử lý thính giác', rows: [
    'Không hiểu được hướng dẫn bằng lời dù đơn giản. Không phản hồi tên gọi.',
    'Xử lý ngôn ngữ nói rất chậm. Cần nhắc lại nhiều lần. Không hiểu câu phức.',
    'Hiểu được chỉ dẫn 1–2 bước quen thuộc. Chậm xử lý trong môi trường ồn ào.',
    'Hiểu được hầu hết chỉ dẫn thông thường. Xử lý tốt trong môi trường yên tĩnh.',
    'Xử lý thính giác tốt. Hiểu chỉ dẫn đa bước. Không ảnh hưởng đáng kể bởi tiếng ồn.',
  ]},
  visual_processing: { name: 'Visual Processing — Xử lý thị giác', rows: [
    'Không nhận ra vật thể, hình ảnh, hoặc biểu tượng quen thuộc. Không phân biệt màu sắc, hình dạng cơ bản.',
    'Xử lý thị giác rất hạn chế. Nhận ra vật thể quen nhưng không nhận ra hình ảnh đại diện.',
    'Nhận ra hình ảnh và biểu tượng quen. Chậm quét thông tin thị giác.',
    'Xử lý thị giác đủ cho học tập cơ bản. Đọc hình ảnh, biểu đồ đơn giản.',
    'Xử lý thị giác tốt. Đọc và giải thích thông tin thị giác đa dạng. Phân biệt chi tiết tốt.',
  ]},
  wm_link: { name: 'Working Memory Link — Kết nối trí nhớ làm việc', rows: [
    'Không giữ được thông tin trong khi thực hiện nhiệm vụ. Quên ngay lập tức bước tiếp theo.',
    'Trí nhớ làm việc rất hạn chế. Chỉ giữ được 1 thông tin tại một thời điểm. Mất hướng khi bị gián đoạn.',
    'Giữ được 1–2 thông tin ngắn hạn. Cần nhắc lại khi nhiệm vụ có nhiều bước.',
    'Trí nhớ làm việc đủ cho nhiệm vụ thông thường. Giữ được 2–3 thông tin.',
    'Trí nhớ làm việc tốt, phù hợp lứa tuổi. Theo dõi đa bước. Kết hợp thông tin từ nhiều nguồn.',
  ]},
  oral_language: { name: 'Oral Language — Ngôn ngữ miệng', rows: [
    'Không có ngôn ngữ nói chức năng. Giao tiếp chỉ qua hành động hoặc không giao tiếp được.',
    'Vốn từ rất hạn chế (dưới 20 từ chức năng). Chủ yếu dùng từ đơn lẻ.',
    'Câu 2–3 từ thường xuyên. Người thân hiểu được, người lạ khó theo.',
    'Câu đầy đủ, giao tiếp hàng ngày được. Người lạ hiểu được phần lớn.',
    'Ngôn ngữ nói phù hợp lứa tuổi. Giao tiếp rõ ràng. Ngữ pháp cơ bản đúng.',
  ]},
  word_finding: { name: 'Word Finding — Tìm từ', rows: [
    'Không truy xuất được từ khi cần. Không thể gọi tên đồ vật quen thuộc khi nhìn thấy.',
    'Tìm từ rất khó khăn. Dừng lại lâu, dùng nhiều cử chỉ thay từ.',
    'Tìm từ chậm và không đều. Gọi tên đồ vật quen được nhưng chậm.',
    'Tìm từ thường tốt với chủ đề quen. Giao tiếp trôi chảy hầu hết thời gian.',
    'Truy xuất từ nhanh và chính xác. Giao tiếp trôi chảy. Vốn từ đa dạng.',
  ]},
  phonemic_awareness: { name: 'Phonemic Awareness — Nhận thức âm vị', rows: [
    'Không nhận ra vần, không phân biệt âm đầu/âm cuối. Không có khái niệm về đơn vị âm thanh.',
    'Nhận ra một số từ giống vần quen thuộc nhưng không phân tích được âm.',
    'Nhận ra vần cơ bản. Xác định được âm đầu của từ đơn giản.',
    'Nhận ra vần tốt. Phân tích âm đầu/âm cuối được. Ghép âm với hỗ trợ ít.',
    'Nhận thức âm vị tốt phù hợp lứa tuổi. Phân tích và tổng hợp âm linh hoạt.',
  ]},
  auditory_memory: { name: 'Auditory Memory — Trí nhớ thính giác', rows: [
    'Không nhớ được thông tin nghe trong vài giây. Không lặp lại được từ vừa nghe.',
    'Nhớ được 1–2 từ riêng lẻ vừa nghe. Quên nhanh thông tin mới.',
    'Nhớ được câu 2–3 từ vừa nghe. Học từ mới qua nghe nhưng cần nhiều lần lặp lại.',
    'Nhớ được câu đầy đủ và chuỗi thông tin ngắn. Nhớ hướng dẫn 2–3 bước.',
    'Trí nhớ thính giác tốt. Nhớ và lặp lại thông tin phức tạp. Học từ mới hiệu quả qua nghe.',
  ]},
  visual_memory: { name: 'Visual Memory — Trí nhớ thị giác', rows: [
    'Không nhận ra đồ vật/hình ảnh quen sau khi không nhìn thấy. Không nhớ vị trí đồ vật.',
    'Trí nhớ thị giác rất kém. Không nhớ được hình ảnh vừa thấy sau vài phút.',
    'Nhớ hình ảnh quen thuộc nhưng không nhớ chi tiết. Khó nhớ hình ảnh/biểu tượng mới.',
    'Trí nhớ thị giác tốt cho vật thể và mặt người quen. Nhớ đường và không gian quen.',
    'Trí nhớ thị giác tốt. Nhớ chi tiết hình ảnh, nhận mặt nhanh. Trí nhớ không gian tốt.',
  ]},
  self_control: { name: 'Self-Control — Tự kiểm soát', rows: [
    'Không có khả năng kiềm chế xung động. Không dừng được khi được yêu cầu. Không chờ đợi được dù trong vài giây.',
    'Kiểm soát xung động rất kém. Chờ đợi dưới 30 giây khó khăn. Dừng hoạt động chỉ khi có can thiệp vật lý.',
    'Kiểm soát xung động không đều. Dừng và chờ được với nhắc nhở liên tục.',
    'Kiểm soát xung động tương đối tốt trong tình huống quen. Chờ đợi được với nhắc nhở vừa phải.',
    'Kiểm soát xung động tốt phù hợp lứa tuổi. Tự điều chỉnh không cần nhắc liên tục.',
  ]},
  behavior: { name: 'Behavior — Hành vi', rows: [
    'Hành vi nguy hiểm thường xuyên (tự làm đau, gây hại người khác). Cần giám sát 1:1 liên tục.',
    'Hành vi thách thức thường xuyên ảnh hưởng đến sinh hoạt. Cần hỗ trợ hành vi chuyên biệt liên tục.',
    'Hành vi thách thức xảy ra thường xuyên nhưng có thể dự đoán (trigger rõ).',
    'Hành vi phù hợp hầu hết thời gian. Hành vi thách thức xảy ra không thường xuyên.',
    'Hành vi phù hợp ở mức lứa tuổi. Không cần hỗ trợ hành vi chuyên biệt.',
  ]},
  social_skills: { name: 'Social Skills — Kỹ năng xã hội', rows: [
    'Không có tương tác xã hội chức năng. Không nhận ra người quen. Không giao tiếp mắt.',
    'Tương tác xã hội rất hạn chế. Chỉ tương tác với người thân thiết trong điều kiện quen thuộc.',
    'Tương tác được với người quen, khó với người lạ. Chơi song song hơn là cùng nhau.',
    'Tương tác xã hội cơ bản tốt. Chơi được với bạn quen. Hiểu quy tắc xã hội thông thường.',
    'Kỹ năng xã hội phù hợp lứa tuổi. Tạo và duy trì quan hệ bạn bè. Đọc tín hiệu xã hội tốt.',
  ]},
  daily_living: { name: 'Daily Living — Sinh hoạt hàng ngày', rows: [
    'Hoàn toàn phụ thuộc trong tất cả sinh hoạt cá nhân (ăn, vệ sinh, mặc).',
    'Phụ thuộc hầu hết. Tham gia được một số bước nhưng không hoàn thành.',
    'Tự thực hiện được một số kỹ năng cơ bản. Cần nhắc nhở và hỗ trợ đáng kể.',
    'Tự thực hiện được hầu hết kỹ năng tự chăm sóc với nhắc nhở vừa phải.',
    'Độc lập trong sinh hoạt hàng ngày phù hợp lứa tuổi.',
  ]},
  math: { name: 'Math — Toán học', rows: [
    'Không có khái niệm số. Không so sánh nhiều/ít. Không đếm được đến 3.',
    'Đếm được đến 10 thuộc lòng nhưng không hiểu số lượng. Kém hơn ít nhất 2 năm so với lứa tuổi.',
    'Hiểu số lượng cơ bản. Cộng/trừ trong phạm vi 10 với vật cụ thể. Kém hơn khoảng 1 năm.',
    'Đạt gần mức lứa tuổi với hỗ trợ vừa phải. Thực hiện được hầu hết bài tập.',
    'Đạt mức lứa tuổi. Thực hiện được bài tập lớp học độc lập.',
  ]},
  writing: { name: 'Writing — Viết', rows: [
    'Không viết được. Không tô theo nét. Không có khả năng cầm bút để tạo hình có chủ đích.',
    'Tô/vẽ được nét cơ bản nhưng không viết chữ được. Kém hơn ít nhất 2 năm.',
    'Viết được chữ cái và số quen nhưng chậm, chữ không đều. Kém hơn khoảng 1 năm.',
    'Viết được với chất lượng chấp nhận được, chậm hơn bạn cùng tuổi.',
    'Viết đạt mức lứa tuổi. Tốc độ và chất lượng phù hợp.',
  ]},
  reading: { name: 'Reading — Đọc hiểu', rows: [
    'Không nhận biết chữ cái hoặc không có khái niệm đọc.',
    'Nhận biết một số chữ cái quen nhưng không đọc từ được. Kém hơn ít nhất 2 năm.',
    'Đọc được từ đơn giản, quen thuộc. Chậm, cần giải mã từng chữ.',
    'Đọc được tài liệu phù hợp lứa tuổi với tốc độ chậm hơn.',
    'Đọc hiểu đạt mức lứa tuổi. Tốc độ và độ chính xác phù hợp.',
  ]},
}

export const SCORE_COLORS = ['#C0392B','#C07010','#B08800','#2A7A4A','#0F5C38']
